# Generated by Django 4.2.3 on 2023-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_qty'),
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='customers', to='products.product'),
        ),
    ]
