# Generated by Django 4.2.3 on 2023-07-14 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAccount', '0002_alter_customer_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
