# Generated by Django 4.2.3 on 2023-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='your city', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='xxxxx-xxxxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='your state', max_length=20),
        ),
    ]
